### ISSUE TITLE
import subprocess error？？？？

### ISSUE THREAD

**Issue by watertianyi** [davisking/pyimageconf2018#1]
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\hjq\\Downloads\\pyimageconf2018-master\\workshop_material\\superfast', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\hjq\\Downloads\\pyimageconf201
8-master\\workshop_material\\superfast\\build\\lib.win-amd64-3.6', '-DPYTHON_EXECUTABLE=D:\\Anaconda3\\envs\\pycv\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\hjq\\Downloads\\pyimageconf
2018-master\\workshop_material\\superfast\\build\\lib.win-amd64-3.6', '-A', 'x64']' returned non-zero exit status 1.
pip setup.py install

**Comment by watertianyi** [comment]
![捕获](https://user-images.githubusercontent.com/29244715/56011867-4c2d1080-5d1c-11e9-82ab-f8004d6d2ca0.PNG)
which demo is running？

**Comment by davisking** [comment]
It’s not a demo. I made this picture manually to illustrate point association logic.
